---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: estanteria
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: estanteria
    spec:
      containers:
      - name: estanteria
        image: victor9889/estanteria:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: estanteria
---
apiVersion: v1
kind: Service
metadata:
  name: estanteria
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: estanteria
